name: "actions-setup-mysql"
description: "Setup MySQL and MariaDB GitHub Action"
author: "Ichinose, Shogo"
inputs:
  mysql-version:
    description: "The version of MySQL and MariaDB"
    default: ""
runs:
  using: "node12"
  main: "lib/setup-mysql.js"
  post: "lib/cleanup-mysql.js"
  post-if: "always()"
branding:
  color: blue
  icon: database
