name: "actions-setup-mysql"
description: "Setup MySQL and MariaDB GitHub Action"
author: "Ichinose, Shogo"
inputs:
  mysql-version:
    description: "The version of MySQL and MariaDB"
    default: ""
  distribution:
    description: "The distribution. valid values are mysql or mariadb."
    default: "mysql"
  auto-start:
    description: "Start MySQL server if it is true."
    default: "true"
  my-cnf:
    description: "my.cnf settings for mysqld"
    default: ""
  root-password:
    description: "password for the root user"
  user:
    description: "name of a new user"
  password:
    description: "password for the new user"
outputs:
  base-dir:
    description: "Returns directory under which the mysql database is being created."
runs:
  using: "node16"
  main: "lib/setup-mysql.js"
  post: "lib/cleanup-mysql.js"
  post-if: "always()"
branding:
  color: blue
  icon: database
