name: Update

on:
  schedule:
    - cron: "23 17 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update
        run: |
          ./.github/update-dependencies.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - name: commit and create a pull request
        uses: shogo82148/actions-commit-and-create-pr@v1
